# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Carsten Schnober
title: Natural Language Processing Researcher & Experienced Software Engineer
email: carschno@gmail.com
website: carschno.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: carschno
github_username:  carschno
stackoverflow_username: "1897839"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: carsten-s-a1aba020
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0001-9139-1577

# Additional icon links
additional_links:
- title: NL eScience Center
  icon: eScience(images/esciencecenter.png)
  url: https://www.esciencecenter.nl/team/carsten-schnober/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Portretten_eScienceCenter_2022_fotoAnneliesVerhelst_072_small.jpg
about_content: | # this will include new lines to allow paragraphs
  I have been a research software engineer for many years in academic institutions and industry.
  That means I bring state-of-the-art technology from <mark>Natural Language Processing</mark>, Machine Learning, and <mark>Deep Learning</mark>
  to practical use.
  This implies developing software by highest standards, tailored to the needs of users and other stakeholders,
  including requirements analysis, implementation, and deployment.

  - Defining problems and possible solutions in close communication
  - Agile development approach
  - Advanced <mark>Artificial Intelligence</mark> solutions, scientifically grounded
  - Build what is needed, re-use what exists
  - Cloud and system engineering (AWS, Linux etc.), open-source software.

  
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Netherlands eScience Center <img src="images/esciencecenter.png" alt="eScience Center Logo" height=30 title="NL eScience Center">
        link: www.esciencecenter.nl
        # link_text: boringcompany.com
        sub_title: Research Software Engineer
        caption: October 2022 - Present
        quote: >
          Academic research, powered by pioneering software
        description: | # this will include new lines to allow paragraphs
            Lead engineer in research projects:
            - [Semantics of Sustainability](https://research-software-directory.org/projects/the-semantics-of-sustainability):
            development and application of <mark>large language models (LLMs)</mark>, incorporating temporal information
            - [Leveraging AI for HTR post-correction](https://research-software-directory.org/projects/lahter):
            development and application of NLP and machine learning for improving digitized handwritten texts , within the [Globalise project](https://globalise.huygens.knaw.nl/).

      - layout: left
        title: <img src="https://www.wizenoze.com/wp-content/uploads/2021/11/logo.svg" alt="Wizenoze Logo" height=30 title="Wizenoze">
        link: www.wizenoze.com
        # link_text: boringcompany.com
        sub_title: Senior NLP Research Software Engineer
        caption: March 2021 - October 2022
        quote: >
          Delivering educational content that is trustworthy

        description: | # this will include new lines to allow paragraphs
          As a member of the Research and Development team, I was responsible for:

          - Development of a Neural Search Engine for educational purposes
          - Backend software architecture, design and implementation
          - Supervision of Bachelor and Master theses and internships


      - layout: left
        title: <img src="https://static.wixstatic.com/media/4f8123_1d56194d420648ec907078f5fc83ade1~mv2.png/v1/crop/x_0,y_54,w_4420,h_772/fill/w_336,h_58,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Logo%20blue.png" alt="Zeta Alpha Logo" height=30 title="Zeta Alpha">
        link: https://www.zeta-alpha.com/
        # link_text: boringcompany.com
        sub_title: Senior NLP Research Software Engineer
        caption: February 2020 - March 2021
        quote: >
          A smarter way to discover and organize knowledge

        description: | # this will include new lines to allow paragraphs
          I was part of the early team of the newly founded research start-up.
          Tasks included:

          - Architecture, research, development for a (neural) search and recommendations platform
          - Service-based backend design and development, DevOps/MLOps
          - Student intern supervision


      - layout: left
        title: <img src="https://textkernel.careers/wp-content/themes/work-at-textkernel/images/textkernel_logo_new.png" alt="Textkernel Logo" height=30 title="Textkernel">
        link: https://www.textkernel.com/
        # link_text: boringcompany.com
        sub_title: Lead NLP Research Software Engineer
        caption: January 2017 - December 2019
        quote: >
          Machine Intelligence Connecting People and Jobs

        description: | # this will include new lines to allow paragraphs
          In my first job outside the world of academic research, I learned to handle time constraints, team management, and requirements by various stakeholders.

          - Development and improvement of Natural Language Processing models and pipelines
          - Introduce a microservice architecture, based on Kubernetes
          - Joint lead of the R&D team
          - Personal skills training in the _Leadership Development Programme_

      - layout: left
        title: UKP Lab, TU Darmstadt <img src="https://www.informatik.tu-darmstadt.de/media/ukp/logo/ukp_logo.png" alt="UKP Lab Logo" height=50>

        quote: >
          Ubiquituous Knowledge Processing Lab, Technical University Darmstadt
        link: https://www.informatik.tu-darmstadt.de/ukp/
        caption: May 2014 - December 2016
        sub_title: Research Software Engineer, PhD candidate
        description: |
          As a Research Engineer, I worked on academic research in the field of Natural Language Processing and Machine Learning,
          focusing on the upcoming trend towards Deep Learning techniques.
          
          - Lead engineer in the [_Welt der Kinder_ project](http://welt-der-kinder.gei.de/)
          - Core developer of [DKPro](https://dkpro.github.io/), the lab's own NLP framework
          - Supervision of Bachelor and Master theses, student assistants
          - Research topics: deep learning, language modelling, topic modelling, distributed computing

      - layout: left
        title: <img src="https://www.ids-mannheim.de/typo3conf/ext/ids_site/Resources/Public/Images/logo-ids-small.svg" alt="IDS Logo" height=50 title="Institut für Deutsche Sprache">
        link: https://www.ids-mannheim.de/
        # link_text: boringcompany.com
        sub_title: Research Software Engineer
        caption: November 2011 - May 2013
        quote: >
          The Institute for the German Language
        description: | # this will include new lines to allow paragraphs
            - Core developer in the KorAP project, a linguistic search engine for text corpora
            - System architecture, data modelling, query language design, network and storage engineering 


      - layout: left
        title: <img src="https://www.linux-magazin.de/wp-content/uploads/2017/11/linux-magazin-logo.png" alt="Linux-Magazin Logo" height=50 title="Linux-Magazin">
        link: https://www.linux-magazin.de/
        # link_text: boringcompany.com
        sub_title: Tech Writer, Editor, Author
        caption: 2003 - 2014
        quote: >
          Europe's Oldest Magazine for Linux and Open-Source Professionals (since 1995)
        description: | # this will include new lines to allow paragraphs
            I worked for the German and international issues of the Linux Magazine, as well as other publications,
            interchangeably as a (staff) editor and a freelancer.
            The company allowed me to follow a journalistic apprenticeship while working as a writer and editor.
            I later helped building up the newly founded [_Admin-Magazin_](https://www.admin-magazin.de/),
            and worked for the English and Spanish issues of the magazine.

            - Authoring and editorial supervision of external authors
            - Member/lead of the _Software & Programming_ department
            - Coordination between the various German and international publications (_LinuxUser_, _EasyLinux_, _Admin-Magazin_)
            - Software development for internal software


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Edinburgh <img src="https://www.ed.ac.uk/sites/all/themes/uoe/assets/logo.png" alt="University of Edinburgh Logo" height=50>
        caption: 2009 - 2010
        sub_title: MSc Speech & Language Processing
        link: https://www.ed.ac.uk/
        link_text: www.ed.ac.uk
        quote: >
          Europe's highest-ranked university for Natural Language Processing research end education.
        description: | # this will include new lines to allow paragraphs          
          The Speech & Language Processing programme combines elements of linguistics, artificial intelligence, computer science, and engineering and is taught by leading researchers from Linguistics & English Language, the Centre for Speech Technology Research, and the School of Informatics.

      - layout: left
        title: University of Heidelberg <img src="https://backend.uni-heidelberg.de/sites/default/files/site_logo/inverse/logo_1.svg" alt="University Heidelberg Logo" height=50>
        caption: 2006 - 2009
        sub_title: B.A. Computational Linguistics, Applied Computer Science
        link: https://www.uni-heidelberg.de/
        quote: >
          Germany’s oldest university and one of the strongest research universities in all of Europe.
        description: | # this will include new lines to allow paragraphs         
          I followed a programme combining Computational Linguistics (Natural Language Processing) and Applied Software Engineering.


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
